apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-volume
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: app-cfg
      mountPath: "/etc/config"
      readOnly: true
  volumes:
  - name: app-cfg
    configMap:
      name: app-config2
