apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          memory: '128Mi'
          cpu: '25m'
        limits:
          memory: '128Mi'
          cpu: '50m'
    - name: log-aggregator
      image: nginx
      resources:
        requests:
          memory: '128Mi'
          cpu: '25m'
        limits:
          memory: '128Mi'
          cpu: '50m'
