apiVersion: v1
kind: Pod
metadata:
  name: kplabs-adapter-logging
spec:
  containers:
    - name: busy-logging
      image: busybox
      command:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$i: $(date)" >> /var/log/1.log;
            echo "$(date) INFO $i" >> /var/log/2.log;
            i=$((i+1));
            sleep 1;
          done
      volumeMounts:
        - name: log-volume
          mountPath: /var/log
    - name: fluentd
      image: k8s.gcr.io/fluentd-gcp:1.30
      env:
        - name: FLUENTD_ARGS
          value: "-c /etc/fluentd-config/fluentd.conf"
      volumeMounts:
        - name: log-volume
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/fluentd-config
  volumes:
    - name: log-volume
      emptyDir: {}
    - name: config-volume
      configMap:
        name: fluendtd-config