apiVersion: v1
data:
  app-config: |-
    global
        daemon
        maxconn 256

    defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    listen http-in
        bind *:80
        server server1 127.0.0.1:9080 maxconn 32
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kplabs-ambassador-config
