apiVersion: v1
kind: Pod
metadata:
  name: kplabs-ambassador-pod
spec:
  containers:
    - name: legacy-app
      image: mykplabs/kubernetes:nginx
    - name: haproxy-container
      image: haproxy:1.7
      volumeMounts:
      - name: config-volume
        mountPath: /usr/local/etc/haproxy
  volumes:
    - name: config-volume
      configMap:
        name: kplabs-ambassador-config
        items:
        - key: app-config
          path: haproxy.cfg
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: kplabs-busybox-curl
spec:
  containers:
  - name: curl-container
    image: yauritux/busybox-curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']
